### ISSUE TITLE
Can't install this plugin in Intellij IDEA -2017.1.4

### ISSUE THREAD

**Issue by yourgentlesmile** [wso2/siddhi-plugin-idea#10]
**Description:**
I try to install the siddhi plugin in my Idea,but I get some puzzle during this time.
1. Can't find this plugin in idea 's browse repositories.
2. Download the plugin file and install it .but idea show a error message,"Plugin 'Siddhi' is incompatible with this installation". tips:I have tried to install all the version of this plugin 

**Affected Product Version:**
V1.0.0 and V1.1.0
**OS, DB, other environment details and versions:**    
OS Version:Windows 10 ,1703
Idea Version: 2017.1.4
**Steps to reproduce:**
About problem 1 
Just search for "Siddhi" in browse repositories.
About problem 2
Install the plugin in idea which version is 2017.1.4

**Comment by tishan89** [comment]
@RAVEENSR Can you please help out on this?

**Comment by RAVEENSR** [comment]
@yourgentlesmile This plugin supports IntelliJ IDEA version 2017.2.5 and above.(mentioned in [here](https://wso2.github.io/siddhi-plugin-idea/install-plugin/)) So Idea Version: 2017.1.4 is not supported by this plugin. That is why it was not shown in idea 's browse repositories. Update you intellij idea to the version 2.5 or above and install the plugin according to [this.](https://wso2.github.io/siddhi-plugin-idea/install-plugin/)

**Comment by yourgentlesmile** [comment]
Ahhh,Thank you for solving my puzzle. I found that the limit of Idea Version in website when I scroll down it.... so,Thank you again~
