### ISSUE TITLE
Break point is not work when query statement inside the partition

### ISSUE THREAD

**Issue by yourgentlesmile** [wso2/siddhi-plugin-idea#11]
**Description:**
Break point can not put to the query when the query statment inside the partition.
```
1 @App:name("firstrule")
2 @App:description("Description of the plan")
3 @source(type='http',receiver.url = 'http://localhost:8080/exchange',@map(type='json'))
4 define stream exchangeStream(id string, age int);
5 @sink(type='log',@map(type='json'))
6 define stream outputStream(id string, age long);
7 partition with (id of exchangeStream)
8    begin
9          from exchangeStream
10        select id, sum(age) as age
11        insert into inner_outputStream
12  end;
```
As the code shows,I want to put a breakpoint in line 9 but it is not success.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
V1.1.0
**OS, DB, other environment details and versions:**    
IDEA 2017.3.3
**Steps to reproduce:**
Just write a siddhi app with the partition statment and try to put a break point

**Related Issues:**
[Similar issue](https://github.com/wso2/product-sp/issues/95)

**Comment by RAVEENSR** [comment]
@yourgentlesmile  This  is actually not a issue in siddhi-idea-plugin. Currently, Siddhi doesn't has the support to add breakpoints in queries which are inside the partitions. So in both siddhi-idea-plugin and Stream Processor we don't have this feature yet.

**Comment by yourgentlesmile** [comment]
@RAVEENSR Thank you~(＾ω＾)
